CREATE TABLE `board` (
	`id_board` INT(11) NOT NULL AUTO_INCREMENT,
	`id_user` INT(11) NOT NULL DEFAULT '0',
	`user_name` VARCHAR(20) NULL DEFAULT '0',
	`date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`text` VARCHAR(500) NULL DEFAULT '0',
	`title` VARCHAR(50) NULL DEFAULT '',
	PRIMARY KEY (`id_board`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=22
;
